version: '2'
services:
    pegaconnect-app:
        image: pegaconnect
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://pegaconnect-mssql:1433;database=pegaConnect
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pegaconnect-mssql:
        extends:
            file: mssql.yml
            service: pegaconnect-mssql
